package gui.controller;

public enum ActionEnum {

    ACTION_ADD,
    ACTION_RENAME,
    ACTION_REMOVE,
    ACTION_CLOSE,
    ACTION_FOCUS,
    ACTION_REMOVEPROJECT,
    ACTION_SHARE,
    ACTION_SELECTED,
    ACTION_SLOTCHANGED,

}
