
package error;

public enum ErrorEnum {
								//type iz ErrorClass-e
	ERROR_DELETEWS,				//1
	ERROR_SLOTCHILDREN,			//2
	ERROR_NOSELECTEDNODE,		//3
	ERROR_ISNOTDOCUMENT,  		//4
	ERROR_ALREADYPARENT,		//5
	ERROR_ISNOTPROJECT,			//6
	ERROR_REMOVE,				//7
	ERROR_NOSELECTEDSLOT,		//8
	ERROR_NOACTIVEPAGE,			//9
	ERROR_NOTHINGTOSAVE	,		//10
	ERROR_NOSLOTCHOSEN			//11

}
